export const TOC_CONTENTS = [
  { id: 'company-desc', title: '기업개황' },
  { id: 'stock-info', title: '주가정보' },
  { id: 'fin-info', title: '재무정보' },
  { id: 'fin-indic', title: '재무지표' },
];

export const COMPANY_INFO_FIELDS = [
  { key: 'emsecPath', label: { ko: 'EMSEC', en: 'EMSEC' }, span: 2 },
  { key: 'corpNameEn', label: { ko: '회사영문명', en: 'Company Name (EN)' } },
  {
    key: 'corpNameLocal',
    label: { ko: '회사현지명', en: 'Company Name (Local)' },
  },
  { key: 'id', label: { ko: '회사식별번호', en: 'Company ID' } },
  { key: 'corpNameListed', label: { ko: '회사공시명', en: 'Listed Name' } },
  { key: 'stockExchange', label: { ko: '거래소', en: 'Exchange' } },
  { key: 'corpTicker', label: { ko: '종목코드', en: 'Ticker' } },
  { key: 'settlePeriod', label: { ko: '결산주기', en: 'Fiscal Period' } },
  { key: 'homepage', label: { ko: '홈페이지', en: 'Website' } },
  {
    key: 'dateFounded',
    label: { ko: '설립일자', en: 'Founded' },
    type: 'date',
  },
  {
    key: 'dateListed',
    label: { ko: '상장일자', en: 'Listed Date' },
    type: 'date',
  },
  { key: 'statusListing', label: { ko: '상장상태', en: 'Listing Status' } },
  {
    key: 'statusDate',
    label: { ko: '상장상태일', en: 'Status Date' },
    type: 'date',
  },
  { key: 'corpSize', label: { ko: '기업규모', en: 'Company Size' } },
  { key: 'groupName', label: { ko: '그룹계열명', en: 'Group' } },
  { key: 'corpId', label: { ko: '법인식별자', en: 'Corp Identifier' } },
  { key: 'bizId', label: { ko: '사업자식별자', en: 'Business Identifier' } },
  { key: 'ceoName', label: { ko: '대표자명', en: 'CEO' } },
  { key: 'majorHolder', label: { ko: '최대주주', en: 'Major Holder' } },
  { key: 'telNo', label: { ko: '전화번호', en: 'Phone' } },
  { key: 'emailAddr', label: { ko: '메일주소', en: 'Email' } },
  { key: 'country', label: { ko: '국가', en: 'Country' } },
  { key: 'region', label: { ko: '지역', en: 'Region' } },
  { key: 'addrEn', label: { ko: '영문주소', en: 'Address (EN)' }, span: 2 },
  {
    key: 'addrLocal',
    label: { ko: '원문주소', en: 'Address (Local)' },
    span: 2,
  },
  {
    key: 'bizOverview',
    label: { ko: '사업개요', en: 'Business Overview' },
    span: 2,
    multiline: true,
  },
  {
    key: 'salesInfo',
    label: { ko: '매출관련내용', en: 'Sales Info' },
    span: 2,
    multiline: true,
  },
  {
    key: 'corpNameHistory',
    label: { ko: '회사이름 변경내역', en: 'Name Change History' },
    span: 2,
    multiline: true,
  },
  {
    key: 'ceoNameHistory',
    label: { ko: '대표자명 변경내역', en: 'CEO Change History' },
    span: 2,
    multiline: true,
  },
  {
    key: 'cntSuspendedHistory',
    label: { ko: '거래중지이력', en: 'Trading Halt History' },
    span: 2,
    multiline: true,
  },
] as const;

export const STOCK_INFO_FIELDS = [
  {
    key: 'tradeDate',
    label: '거래일자',
    labelEn: 'Date',
    width: 100,
    fixed: true,
    align: 'center',
  },
  {
    key: 'outstandingShares',
    label: '유통주식수',
    labelEn: 'Shares Outstanding',
    width: 100,
    align: 'right',
  },
  {
    key: 'tradeVolume',
    label: '거래량(주)',
    labelEn: 'Volume',
    width: 100,
    align: 'right',
  },
  {
    key: 'priceCloseAdj',
    label: '수정종가',
    labelEn: 'Adj. Close',
    width: 100,
    align: 'right',
    highlight: true,
  },
  {
    key: 'priceOpenAdj',
    label: '수정시가',
    labelEn: 'Adj. Open',
    width: 100,
    align: 'right',
  },
  {
    key: 'priceHighAdj',
    label: '수정고가',
    labelEn: 'Adj. High',
    width: 100,
    align: 'right',
  },
  {
    key: 'priceLowAdj',
    label: '수정저가',
    labelEn: 'Adj. Low',
    width: 100,
    align: 'right',
  },
  {
    key: 'marketCapAdj',
    label: '수정시가총액',
    labelEn: 'Adj Market Cap',
    width: 100,
    align: 'right',
  },
  { key: 'evEnd', label: 'EV', labelEn: 'EV', width: 100, align: 'right' },
  { key: 'perEnd', label: 'PER', labelEn: 'PER', width: 100, align: 'right' },
  { key: 'pbrEnd', label: 'PBR', labelEn: 'PBR', width: 100, align: 'right' },
  { key: 'psrEnd', label: 'PSR', labelEn: 'PSR', width: 100, align: 'right' },
  { key: 'pcrEnd', label: 'PCR', labelEn: 'PCR', width: 100, align: 'right' },
  {
    key: 'evSalesEnd',
    label: 'EV/Sales',
    labelEn: 'EV/Sales',
    width: 100,
    align: 'right',
  },
  {
    key: 'evEbitdaEnd',
    label: 'EV/EBITDA',
    labelEn: 'EV/EBITDA',
    width: 100,
    align: 'right',
  },
];

export const FINANCIAL_INFO_FIELDS = [
  {
    key: 'desc',
    label: '개요',
    fields: [
      { key: 'fiscalNo', label: '기수' },
      { key: 'periodStart', label: '기간시작' },
      { key: 'periodEnd', label: '기간종료' },
      { key: 'periodType', label: '기간단위' },
      { key: 'consolFlag', label: '연결구분' },
      { key: 'reportType', label: '실적구분' },
      { key: 'fiscalYear', label: '사업연도' },
      { key: 'auditOpinion', label: '감사의견' },
      { key: 'creditRating', label: '신용평가등급' },
      { key: 'currency', label: '통화' },
      { key: 'amountUnit', label: '금액단위' },
    ],
  },

  {
    key: 'bs',
    label: '재무상태',
    fields: [
      { key: 'assetsTtl', label: '자산총계' },
      { key: 'assetsCurrent', label: '유동자산소계' },
      { key: 'cashTtl', label: '현금성자산총액' },
      { key: 'arTtl', label: '매출채권총액' },
      { key: 'inventoryTtl', label: '재고자산총액' },
      { key: 'assetsTangibleTtl', label: '유형자산총액' },
      { key: 'assetsIntangibleTtl', label: '무형자산총액' },
      { key: 'liabilitiesTtl', label: '부채총계' },
      { key: 'liabilitiesCurrent', label: '유동부채소계' },
      { key: 'accountsPayableTtl', label: '매입채무총액' },
      { key: 'debtInterestTtl', label: '이자발생부채총액' },
      { key: 'equityTtl', label: '자본총계' },
      { key: 'equityCommon', label: '자기자본' },
      { key: 'capitalPaidIn', label: '자본금' },
      { key: 'capitalPreferred', label: '우선주자본금' },
      { key: 'capitalCommon', label: '보통주자본금' },
      { key: 'rtdEarningsCtrl', label: '이익잉여금지배' },
      { key: 'rtdEarningsTtl', label: '이익잉여금총액' },
      { key: 'capitalSurplusCtrl', label: '자본잉여금지배' },
      { key: 'capitalSurplusTtl', label: '자본잉여금총액' },
      { key: 'surplusTtl', label: '잉여금총계' },
      { key: 'netBorrowing', label: '순차입금' },
      { key: 'nwc', label: '순운전자본' },
    ],
  },

  {
    key: 'cf',
    label: '현금흐름',
    fields: [
      { key: 'cfoTtl', label: '영업현금흐름소계' },
      { key: 'depreciationTtl', label: '감가상각총액' },
      { key: 'cfiTtl', label: '투자현금흐름소계' },
      { key: 'capex', label: '자본적지출총액' },
      { key: 'cffTtl', label: '재무현금흐름소계' },
      { key: 'dividendsCommon', label: '보통주배당금' },
      { key: 'dividendsPreferred', label: '우선주배당금' },
      { key: 'dividendsTtl', label: '배당금총액' },
      { key: 'fcf', label: '잉여현금흐름' },
      { key: 'fcff', label: '기업잉여현금흐름' },
    ],
  },

  {
    key: 'pl',
    label: '손익계산',
    fields: [
      { key: 'revenue', label: '매출액' },
      { key: 'cogs', label: '매출원가' },
      { key: 'sgaTtl', label: '판관비총액' },
      { key: 'operatingProfit', label: '영업이익' },
      { key: 'ebt', label: 'EBT' },
      { key: 'interestExpenseTtl', label: '이자비용총액' },
      { key: 'taxExpense', label: '법인세비용' },
      { key: 'netIncome', label: '당기순이익' },
      { key: 'netIncomeCtrl', label: '당기순이익지배' },
      { key: 'ebit', label: 'EBIT' },
      { key: 'ebitda', label: 'EBITDA' },
    ],
  },

  {
    key: 'shares',
    label: '주식',
    fields: [
      { key: 'parValue', label: '액면가' },
      { key: 'sharesCommon', label: '보통주발행주식수' },
      { key: 'sharesPreferred', label: '우선주발행주식수' },
      { key: 'sharesCommonAvg', label: '보통주평균발행수' },
      { key: 'sharesPreferredAvg', label: '우선주평균발행수' },
      { key: 'sharesIssued', label: '발행주식수' },
      { key: 'sharesIssuedAvg', label: '평균발행주식수' },
      { key: 'sharesTreasury', label: '자기주식수' },
    ],
  },
];

export const FINANCIAL_INDIC_FIELDS = [
  {
    key: 'desc',
    label: '개요',
    fields: [
      { key: 'fiscalNo', label: '기수' },
      { key: 'periodStart', label: '기간시작' },
      { key: 'periodEnd', label: '기간종료' },
      { key: 'fiscalYear', label: '사업연도' },
      { key: 'currency', label: '통화' },
      { key: 'amountUnit', label: '금액단위' },
    ],
  },
  {
    key: 'mktcap',
    label: '시총',
    fields: [
      { key: 'currency', label: '통화' },
      { key: 'marketCapEnd', label: '시가총액기말' },
      { key: 'marketCapOpen', label: '시가총액시가' },
      { key: 'marketCapHigh', label: '시가총액고가' },
      { key: 'marketCapLow', label: '시가총액저가' },
      { key: 'marketCapAvg', label: '시가총액평균' },
      { key: 'evEnd', label: 'EV기말' },
      { key: 'evEndAvg', label: 'EV기말평균' },
    ],
  },
  {
    key: 'perShare',
    label: 'PerShare',
    fields: [
      { key: 'sps', label: 'SPS' },
      { key: 'ebitdaps', label: 'EBITDAPS' },
      { key: 'eps', label: 'EPS' },
      { key: 'cfps', label: 'CFPS' },
      { key: 'bps', label: 'BPS' },
    ],
  },
  {
    key: 'multiple',
    label: 'Multiple',
    fields: [
      { key: 'psrEnd', label: 'PSR기말' },
      { key: 'psrAvg', label: 'PSR평균' },
      { key: 'perEnd', label: 'PER기말' },
      { key: 'perAvg', label: 'PER평균' },
      { key: 'pcrEnd', label: 'PCR기말' },
      { key: 'pcrAvg', label: 'PCR평균' },
      { key: 'evSalesEnd', label: 'EV/Sales기말' },
      { key: 'evSalesAvg', label: 'EV/Sales평균' },
      { key: 'evEbitdaEnd', label: 'EV/EBITDA기말' },
      { key: 'evEbitdaAvg', label: 'EV/EBITDA평균' },
      { key: 'pbrEnd', label: 'PBR기말' },
      { key: 'pbrAvg', label: 'PBR평균' },
    ],
  },
  {
    key: 'profitability',
    label: '수익성',
    fields: [
      { key: 'gpm', label: '매출총이익률' },
      { key: 'opm', label: '영업이익률' },
      { key: 'npm', label: '순이익률' },
      { key: 'ebitdaMargin', label: 'EBITDA마진율' },
      { key: 'roe', label: 'ROE' },
      { key: 'roa', label: 'ROA' },
      { key: 'roic', label: 'ROIC' },
      { key: 'wacc', label: 'WACC' },
    ],
  },
  {
    key: 'growth',
    label: '성장성',
    fields: [
      { key: 'revenueGrowthRate', label: '매출증가율' },
      { key: 'operatingProfitGrowthRate', label: '영업이익증가율' },
      { key: 'ebitdaGrowthRate', label: 'EBITDA증가율' },
      { key: 'netIncomeGrowthRate', label: '순이익증가율' },
      { key: 'cfoGrowthRate', label: '영업현금흐름증가율' },
      { key: 'equityGrowthRate', label: '자기자본증가율' },

      { key: 'operatingMarginGrowthRate', label: '영업이익률증가율' },
      { key: 'ebitdaMarginGrowthRate', label: 'EBITDA마진율증가율' },
      { key: 'netMarginGrowthRate', label: '순이익률증가율' },

      { key: 'revenueStatus', label: '매출증감상태' },
      { key: 'operatingProfitStatus', label: '영업이익증감상태' },
      { key: 'ebitdaStatus', label: 'EBITDA증감상태' },
      { key: 'netIncomeStatus', label: '순이익증감상태' },

      { key: 'revenuePattern3y', label: '매출증감패턴3년' },
      { key: 'operatingProfitPattern3y', label: '영업이익증감패턴3년' },
      { key: 'ebitdaPattern3y', label: 'EBITDA증감패턴3년' },
      { key: 'netIncomePattern3y', label: '순이익증감패턴3년' },

      { key: 'revenueCagr3y', label: '매출CAGR3년' },
      { key: 'operatingProfitCagr3y', label: '영업이익CAGR3년' },
      { key: 'operatingMarginCagr3y', label: '영업이익률CAGR3년' },
      { key: 'ebitdaCagr3y', label: 'EBITDACAGR3년' },
      { key: 'ebitdaMarginCagr3y', label: 'EBITDA마진율CAGR3년' },
      { key: 'netIncomeCagr3y', label: '순이익CAGR3년' },
      { key: 'netMarginCagr3y', label: '순이익률CAGR3년' },
      { key: 'cfoCagr3y', label: '영업현금흐름CAGR3년' },
      { key: 'equityCagr3y', label: '자기자본CAGR3년' },

      { key: 'revenueCagr5y', label: '매출CAGR5년' },
      { key: 'operatingProfitCagr5y', label: '영업이익CAGR5년' },
      { key: 'operatingMarginCagr5y', label: '영업이익률CAGR5년' },
      { key: 'ebitdaCagr5y', label: 'EBITDACAGR5년' },
      { key: 'ebitdaMarginCagr5y', label: 'EBITDA마진율CAGR5년' },
      { key: 'netIncomeCagr5y', label: '순이익CAGR5년' },
      { key: 'netMarginCagr5y', label: '순이익률CAGR5년' },
      { key: 'cfoCagr5y', label: '영업현금흐름CAGR5년' },
      { key: 'equityCagr5y', label: '자기자본CAGR5년' },
    ],
  },
  {
    key: 'stability',
    label: '안정성',
    fields: [
      { key: 'debtToEquityRatio', label: '부채비율' },
      { key: 'equityRatio', label: '자기자본비율' },
      { key: 'netDebtRatio', label: '순차입금비율' },
      { key: 'currentRatio', label: '유동비율' },
      { key: 'currentLiabilitiesRatio', label: '유동부채비율' },
      { key: 'capitalRetentionRatio', label: '자본유보율' },
      { key: 'interestCoverageRatio', label: '이자보상배율' },

      { key: 'debtToEquityRatioGrowthRate', label: '부채비율증가율' },
      { key: 'equityRatioGrowthRate', label: '자기자본비율증가율' },
      { key: 'netDebtRatioGrowthRate', label: '순차입금비율증가율' },

      { key: 'debtToEquityRatioCagr3y', label: '부채비율CAGR3년' },
      { key: 'equityRatioCagr3y', label: '자기자본비율CAGR3년' },
      { key: 'netDebtRatioCagr3y', label: '순차입금비율CAGR3년' },

      { key: 'debtToEquityRatioCagr5y', label: '부채비율CAGR5년' },
      { key: 'equityRatioCagr5y', label: '자기자본비율CAGR5년' },
      { key: 'netDebtRatioCagr5y', label: '순차입금비율CAGR5년' },
    ],
  },
  {
    key: 'activity',
    label: '활동성',
    fields: [
      { key: 'ttlAssetTurnover', label: '총자산회전율' },
      { key: 'ttlLiabilityTurnover', label: '총부채회전율' },
      { key: 'equityTurnover', label: '자기자본회전율' },
      { key: 'fixedAssetTurnover', label: '유형자산회전율' },
      { key: 'arTurnover', label: '매출채권회전율' },
      { key: 'inventoryTurnover', label: '재고자산회전율' },
      { key: 'apTurnover', label: '매입채무회전율' },
    ],
  },
  {
    key: 'return',
    label: '환원성',
    fields: [{ key: 'dividendPayoutRatio', label: '배당성향' }],
  },
];
